name: Spawnr
main: nl.kosinus.spawnr.Spawnr
version: 0.1
authors: [kosinus, amd3th]
description: Sets player initial spawn and respawn location to exact coordinates that OP sets.
commands:
  setspawn:
      description: Sets a new spawn location.
      usage: /<command> [ global | <player> ]
  spawn:
      description: Teleport to the spawn point.
      usage: /<command>